cmake_minimum_required(VERSION 3.24)

foreach(_required IN ITEMS INPUT_DIR OUTPUT_HEADER OUTPUT_SOURCE NAMESPACE HEADER_BASENAME)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "GenerateWebResources.cmake requires -D${_required}=...")
    endif()
endforeach()

if(NOT IS_DIRECTORY "${INPUT_DIR}")
    message(FATAL_ERROR "Web resource input directory does not exist: ${INPUT_DIR}")
endif()

function(_webview_gui_cpp_escape input output)
    set(_value "${input}")
    string(REPLACE "\\" "\\\\" _value "${_value}")
    string(REPLACE "\"" "\\\"" _value "${_value}")
    set(${output} "${_value}" PARENT_SCOPE)
endfunction()

function(_webview_gui_mime path output)
    get_filename_component(_extension "${path}" LAST_EXT)
    string(TOLOWER "${_extension}" _extension)
    if(_extension STREQUAL ".html" OR _extension STREQUAL ".htm")
        set(_mime "text/html; charset=utf-8")
    elseif(_extension STREQUAL ".js" OR _extension STREQUAL ".mjs")
        set(_mime "application/javascript; charset=utf-8")
    elseif(_extension STREQUAL ".css")
        set(_mime "text/css; charset=utf-8")
    elseif(_extension STREQUAL ".json" OR _extension STREQUAL ".map")
        set(_mime "application/json; charset=utf-8")
    elseif(_extension STREQUAL ".svg")
        set(_mime "image/svg+xml")
    elseif(_extension STREQUAL ".png")
        set(_mime "image/png")
    elseif(_extension STREQUAL ".jpg" OR _extension STREQUAL ".jpeg")
        set(_mime "image/jpeg")
    elseif(_extension STREQUAL ".webp")
        set(_mime "image/webp")
    elseif(_extension STREQUAL ".gif")
        set(_mime "image/gif")
    elseif(_extension STREQUAL ".ico")
        set(_mime "image/x-icon")
    elseif(_extension STREQUAL ".woff")
        set(_mime "font/woff")
    elseif(_extension STREQUAL ".woff2")
        set(_mime "font/woff2")
    elseif(_extension STREQUAL ".ttf")
        set(_mime "font/ttf")
    elseif(_extension STREQUAL ".otf")
        set(_mime "font/otf")
    elseif(_extension STREQUAL ".wasm")
        set(_mime "application/wasm")
    elseif(_extension STREQUAL ".txt")
        set(_mime "text/plain; charset=utf-8")
    else()
        set(_mime "application/octet-stream")
    endif()
    set(${output} "${_mime}" PARENT_SCOPE)
endfunction()

file(GLOB_RECURSE _resources LIST_DIRECTORIES FALSE RELATIVE "${INPUT_DIR}" "${INPUT_DIR}/*")
list(SORT _resources)
list(LENGTH _resources _resource_count)
if(_resource_count EQUAL 0)
    message(FATAL_ERROR "Vite produced no resources in ${INPUT_DIR}")
endif()

get_filename_component(_header_dir "${OUTPUT_HEADER}" DIRECTORY)
get_filename_component(_source_dir "${OUTPUT_SOURCE}" DIRECTORY)
file(MAKE_DIRECTORY "${_header_dir}" "${_source_dir}")

set(_header "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n#include <string_view>\n\nnamespace ${NAMESPACE} {\n\nstruct Resource {\n    std::string_view path;\n    std::string_view mimeType;\n    const std::uint8_t *data;\n    std::size_t size;\n};\n\n[[nodiscard]] const Resource *find(std::string_view path) noexcept;\n\n} // namespace ${NAMESPACE}\n")
file(WRITE "${OUTPUT_HEADER}" "${_header}")

file(WRITE "${OUTPUT_SOURCE}" "#include \"${HEADER_BASENAME}\"\n\n#include <array>\n\nnamespace {\n")

set(_entries "")
foreach(_relative IN LISTS _resources)
    set(_absolute "${INPUT_DIR}/${_relative}")
    file(SIZE "${_absolute}" _size)
    file(READ "${_absolute}" _hex HEX)
    string(SHA256 _hash "${_relative}")
    string(SUBSTRING "${_hash}" 0 16 _symbol)

    set(_bytes "")
    string(LENGTH "${_hex}" _hex_length)
    if(_hex_length GREATER 0)
        math(EXPR _last "${_hex_length} - 2")
        foreach(_offset RANGE 0 ${_last} 2)
            string(SUBSTRING "${_hex}" ${_offset} 2 _byte)
            string(APPEND _bytes "0x${_byte},")
        endforeach()
    else()
        set(_bytes "0x00,")
    endif()

    file(APPEND "${OUTPUT_SOURCE}"
        "alignas(16) const std::uint8_t resource_${_symbol}[] = {${_bytes}};\n")

    _webview_gui_mime("${_relative}" _mime)
    _webview_gui_cpp_escape("/${_relative}" _path_literal)
    _webview_gui_cpp_escape("${_mime}" _mime_literal)
    string(APPEND _entries
        "    Resource{\"${_path_literal}\", \"${_mime_literal}\", resource_${_symbol}, ${_size}u},\n")
endforeach()

file(APPEND "${OUTPUT_SOURCE}" "}\n\nnamespace ${NAMESPACE} {\nnamespace {\nconstexpr std::array<Resource, ${_resource_count}> kResources{{\n${_entries}}};\n}\n\nconst Resource *find(std::string_view path) noexcept {\n    for (const auto &resource : kResources) {\n        if (resource.path == path)\n            return &resource;\n    }\n    return nullptr;\n}\n\n} // namespace ${NAMESPACE}\n")
